use cfa_mixer;

create table PROVIDER_CODE_RULE (
	ID bigint not null auto_increment,
    RULE_START_DATE DATETIME,
	FLIGHT_PROVIDER varChar(20),
    AIRLINE varchar(20),
    FLIGHT_TYPE varchar(20),
    EVENT_TYPE varchar(20),
    FLIGHT_CONCILIATION varchar(20),
    primary key (ID)
);

create table PROVIDER_CODE_RULE_AUD (
	ID bigint not null,
    REV integer not null,
    REVTYPE tinyint,
    RULE_START_DATE DATETIME,
	FLIGHT_PROVIDER varChar(20),
    AIRLINE varchar(20),
    FLIGHT_TYPE varchar(20),
    EVENT_TYPE varchar(20),
    FLIGHT_CONCILIATION varchar(20),
    primary key (ID, REV)
);

create table PROVIDER_CODE_RULE_PENDING_APPROVAL (
	ID bigint not null auto_increment,
	FLIGHT_PROVIDER varChar(20),
    RULE_START_DATE DATETIME,
    AIRLINE varchar(20),
    FLIGHT_TYPE varchar(20),
    EVENT_TYPE varchar(20),
    FLIGHT_CONCILIATION varchar(20),
    VERSION int,
    primary key (ID)
);

create table PROVIDER_CODE_RULE_ACTIVE (
	ID bigint not null auto_increment,
	FLIGHT_PROVIDER varChar(20),
    AIRLINE varchar(20),
    RULE_START_DATE DATETIME,
    FLIGHT_TYPE varchar(20),
    EVENT_TYPE varchar(20),
    FLIGHT_CONCILIATION varchar(20),
    VERSION int,
    primary key (ID)
);

create table PROVIDER_CODE_RULE_ACTIVE_AUD (
	ID bigint not null auto_increment,
	REV integer not null,
    REVTYPE tinyint,
    RULE_START_DATE DATETIME,
	FLIGHT_PROVIDER varChar(20),
    AIRLINE varchar(20),
    FLIGHT_TYPE varchar(20),
    EVENT_TYPE varchar(20),
    FLIGHT_CONCILIATION varchar(20),
    VERSION int, 
	primary key (ID, REV)
);

ALTER TABLE PROVIDER_CODE_RULE add column FLIGHT_PROVIDER_DESCRIPTION varchar(40);
ALTER TABLE PROVIDER_CODE_RULE_AUD add column FLIGHT_PROVIDER_DESCRIPTION varchar(40);
ALTER TABLE PROVIDER_CODE_RULE_PENDING_APPROVAL add column FLIGHT_PROVIDER_DESCRIPTION varchar(40);
ALTER TABLE PROVIDER_CODE_RULE_ACTIVE add column FLIGHT_PROVIDER_DESCRIPTION varchar(40);
ALTER TABLE PROVIDER_CODE_RULE_ACTIVE_AUD add column FLIGHT_PROVIDER_DESCRIPTION varchar(40);

ALTER TABLE PROVIDER_CODE_RULE add column EVENT_TYPE_DESCRIPTION varchar(40);
ALTER TABLE PROVIDER_CODE_RULE_AUD add column EVENT_TYPE_DESCRIPTION varchar(40);
ALTER TABLE PROVIDER_CODE_RULE_PENDING_APPROVAL add column EVENT_TYPE_DESCRIPTION varchar(40);
ALTER TABLE PROVIDER_CODE_RULE_ACTIVE add column EVENT_TYPE_DESCRIPTION varchar(40);
ALTER TABLE PROVIDER_CODE_RULE_ACTIVE_AUD add column EVENT_TYPE_DESCRIPTION varchar(40);

ALTER TABLE PROVIDER_CODE_RULE add column FLIGHT_TYPE_DESCRIPTION varchar(40);
ALTER TABLE PROVIDER_CODE_RULE_AUD add column EVENT_TYPE_DESCRIPTION varchar(40);
ALTER TABLE PROVIDER_CODE_RULE_PENDING_APPROVAL add column EVENT_TYPE_DESCRIPTION varchar(40);
ALTER TABLE PROVIDER_CODE_RULE_ACTIVE add column EVENT_TYPE_DESCRIPTION varchar(40);
ALTER TABLE PROVIDER_CODE_RULE_ACTIVE_AUD add column EVENT_TYPE_DESCRIPTION varchar(40);

insert INTO CATALOGUE_TYPE (DESCRIPTION) values("AEROLINEA");
insert INTO CATALOGUE_TYPE (DESCRIPTION) values("CONCILIACION VUELO");
insert INTO CATALOGUE_TYPE (DESCRIPTION) values("PROVEEDOR VUELO");
insert INTO CATALOGUE_TYPE (DESCRIPTION) values("TIPO DE EVENTO");
insert INTO CATALOGUE_TYPE (DESCRIPTION) values("TIPO DE VUELO");


insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("*", "*", 11);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("JJ", "JJ", 11);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("P3", "P3", 11);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("G3", "G3", 11);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("ZZ", "ZZ", 11);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("AD", "AD", 11);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("4O", "4O", 11);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("Y4", "Y4", 11);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("VB", "VB", 11);


insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("BSP", "BSP", 12);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("PSR", "PSR", 12);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("PS2", "PS2", 12);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("GOL", "GOL", 12);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("SLX", "SLX", 12);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("SL2", "SL2", 12);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("AZD", "AZD", 12);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("INT", "INT", 12);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("VIV", "VOL", 12);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("TRV", "TRV", 12);

insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("SLX", "Sete", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("DSP", "DSP", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("WDS", "Worldspan", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("VOL", "Volaris", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("VIV", "VivaAerobus", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("TAM", "TAM", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("WBJ", "WEBJET", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("GDS", "Sabre", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("GOL", "GOL", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("SOV", "Special Offer Vuelos", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("PSR", "PASSAREDO", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("OC6", "AVIANCA", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("AZD", "AZUL", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("AIJ", "Interjet", 13);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("ADS", "Amadeus", 13);

insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("*", "*", 14);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("CANCEL", "Cancelación", 14);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("MODIFY", "Modificación", 14);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("SALE", "Venta", 14);

insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("DOMESTIC", "Doméstico", 15);
insert INTO CATALOGUE (CODE, DESCRIPTION, CATALOGUE_TYPE_ID) values("INTERNATIONAL", "Internacional", 15);




