use cfa_mixer;

ALTER TABLE RULE_SELL_TYPE ADD COLUMN COUNTRY_CODE_DESTINY VARCHAR(20) NULL DEFAULT "*" AFTER COUNTRY_CODE_SITE;
ALTER TABLE RULE_SELL_TYPE_AUD ADD COLUMN COUNTRY_CODE_DESTINY VARCHAR(20) NULL DEFAULT "*" AFTER COUNTRY_CODE_SITE;
ALTER TABLE RULE_SELL_TYPE_ACTIVE ADD COLUMN COUNTRY_CODE_DESTINY VARCHAR(20) NULL DEFAULT "*" AFTER COUNTRY_CODE_SITE;
ALTER TABLE RULE_SELL_TYPE_ACTIVE_AUD ADD COLUMN COUNTRY_CODE_DESTINY VARCHAR(20) NULL DEFAULT "*" AFTER COUNTRY_CODE_SITE;
ALTER TABLE RULE_SELL_TYPE_PENDING_APPROVAL ADD COLUMN COUNTRY_CODE_DESTINY VARCHAR(20) NULL DEFAULT "*" AFTER COUNTRY_CODE_SITE;

ALTER TABLE `RULE_SELL_TYPE` 
DROP INDEX `IDX_RULE_SELL_TYPE` ,
ADD UNIQUE INDEX `IDX_RULE_SELL_TYPE` (`PRODUCT_TYPE` ASC, `COUNTRY_CODE_SITE` ASC, `COUNTRY_CODE_PROVIDER` ASC, `ASSISTANCE_TYPE` ASC, `AFFILIATED_AGENCY` ASC, `RULE_START_DATE` ASC, `COUNTRY_CODE_DESTINY` ASC);