use cfa_mixer;

ALTER TABLE RULE_SELL_TYPE_PENDING_APPROVAL ADD COLUMN RULE_START_DATE datetime;

ALTER TABLE OM_LEGAL_ENTITY_PP_PENDING_APPROVAL ADD COLUMN RULE_START_DATE datetime;

ALTER TABLE PAYMENT_REFUND_PENDING_APPROVAL ADD COLUMN RULE_START_DATE datetime;

CREATE UNIQUE INDEX IDX_OM_LEGAL_ENTITY_PP ON OM_LEGAL_ENTITY_PP (COUNTRY_CODE_SITE,PRODUCT_TYPE,SELL_TYPE,AFILIATED);

alter table OM_LEGAL_ENTITY_PP add constraint FK_LEGAL_ENTITY foreign key (LEGAL_ENTITY_ID) references LEGAL_ENTITY (ID);

CREATE UNIQUE INDEX IDX_PAYMENT_REFUND ON PAYMENT_REFUND (COUNTRY_CODE_SITE,PRODUCT_TYPE,CURRENCY_TYPE,PAYMENT_METHOD,COLECCTION_CHANNEL,MERCHANT);

alter table PAYMENT_REFUND add constraint FK_PAYMENT_REFUND_LEGAL_ENTITY foreign key (LEGAL_ENTITY_ID) references LEGAL_ENTITY (ID);