use cfa_mixer;

ALTER TABLE OM_LEGAL_ENTITY_PP ADD COLUMN COLLECTION_CHANNEL varchar(50) default 'ALL' AFTER SELL_TYPE_DESCRIPTION;
ALTER TABLE OM_LEGAL_ENTITY_PP_AUD ADD COLUMN COLLECTION_CHANNEL varchar(50) default 'ALL' AFTER SELL_TYPE_DESCRIPTION;
ALTER TABLE OM_LEGAL_ENTITY_PP_ACTIVE ADD COLUMN COLLECTION_CHANNEL varchar(50) default 'ALL' AFTER SELL_TYPE_DESCRIPTION;
ALTER TABLE OM_LEGAL_ENTITY_PP_ACTIVE_AUD ADD COLUMN COLLECTION_CHANNEL varchar(50) default 'ALL' AFTER SELL_TYPE_DESCRIPTION;
ALTER TABLE OM_LEGAL_ENTITY_PP_PENDING_APPROVAL ADD COLUMN COLLECTION_CHANNEL varchar(50) default 'ALL' AFTER SELL_TYPE_DESCRIPTION;

ALTER TABLE OM_LEGAL_ENTITY_PP ADD COLUMN COLLECTION_CHANNEL_DESCRIPTION varchar(100) default '*' AFTER COLLECTION_CHANNEL;
ALTER TABLE OM_LEGAL_ENTITY_PP_AUD ADD COLUMN COLLECTION_CHANNEL_DESCRIPTION varchar(100) default '*' AFTER COLLECTION_CHANNEL;
ALTER TABLE OM_LEGAL_ENTITY_PP_ACTIVE ADD COLUMN COLLECTION_CHANNEL_DESCRIPTION varchar(100) default '*' AFTER COLLECTION_CHANNEL;
ALTER TABLE OM_LEGAL_ENTITY_PP_ACTIVE_AUD ADD COLUMN COLLECTION_CHANNEL_DESCRIPTION varchar(100) default '*' AFTER COLLECTION_CHANNEL;
ALTER TABLE OM_LEGAL_ENTITY_PP_PENDING_APPROVAL ADD COLUMN COLLECTION_CHANNEL_DESCRIPTION varchar(100) default '*' AFTER COLLECTION_CHANNEL;

ALTER TABLE OM_LEGAL_ENTITY_PP ADD COLUMN MERCHANT_ID varchar(50) default 'ALL' AFTER COLLECTION_CHANNEL_DESCRIPTION;
ALTER TABLE OM_LEGAL_ENTITY_PP_AUD ADD COLUMN MERCHANT_ID varchar(50) default 'ALL' AFTER COLLECTION_CHANNEL_DESCRIPTION;
ALTER TABLE OM_LEGAL_ENTITY_PP_ACTIVE ADD COLUMN MERCHANT_ID varchar(50) default 'ALL' AFTER COLLECTION_CHANNEL_DESCRIPTION;
ALTER TABLE OM_LEGAL_ENTITY_PP_ACTIVE_AUD ADD COLUMN MERCHANT_ID varchar(50) default 'ALL' AFTER COLLECTION_CHANNEL_DESCRIPTION;
ALTER TABLE OM_LEGAL_ENTITY_PP_PENDING_APPROVAL ADD COLUMN MERCHANT_ID varchar(50) default 'ALL' AFTER COLLECTION_CHANNEL_DESCRIPTION;

ALTER TABLE OM_LEGAL_ENTITY_PP ADD COLUMN MERCHANT_ID_DESCRIPTION varchar(100) default '*' AFTER MERCHANT_ID;
ALTER TABLE OM_LEGAL_ENTITY_PP_AUD ADD COLUMN MERCHANT_ID_DESCRIPTION varchar(100) default '*' AFTER MERCHANT_ID;
ALTER TABLE OM_LEGAL_ENTITY_PP_ACTIVE ADD COLUMN MERCHANT_ID_DESCRIPTION varchar(100) default '*' AFTER MERCHANT_ID;
ALTER TABLE OM_LEGAL_ENTITY_PP_ACTIVE_AUD ADD COLUMN MERCHANT_ID_DESCRIPTION varchar(100) default '*' AFTER MERCHANT_ID;
ALTER TABLE OM_LEGAL_ENTITY_PP_PENDING_APPROVAL ADD COLUMN MERCHANT_ID_DESCRIPTION varchar(100) default '*' AFTER MERCHANT_ID;