use cfa_mixer;

drop index IDX_OM_LEGAL_ENTITY_PP on OM_LEGAL_ENTITY_PP;

CREATE UNIQUE INDEX IDX_OM_LEGAL_ENTITY_PP ON OM_LEGAL_ENTITY_PP (COUNTRY_CODE_SITE,PRODUCT_TYPE,SELL_TYPE,AFILIATED,COLLECTION_CHANNEL,MERCHANT_ID);
