use cfa_mixer;

create table EVENT_REPORT(
	ID bigint not null auto_increment,
  EVENT_DATE DATETIME,
	REQUEST_TIME bigint,
	EVENT_STATUS varchar(20),
	ENTITY_TYPE VARCHAR(100),
	CLASS_NAME varchar(100),
  METHOD_NAME varchar(100),
  TOKEN_REQ_RES varchar(36),
  REQUEST_HOST varchar(100),
	REQUEST_XCLIENT varchar(100),
	REQUEST_UOW varchar(100),
	REQUEST_URL VARCHAR (255),
     primary key (ID)
);

ALTER TABLE EVENT_REPORT ADD INDEX (EVENT_DATE);

ALTER TABLE LEGAL_ENTITY ADD COLUMN OPERATIONAL_TRX BIT DEFAULT 0;
ALTER TABLE LEGAL_ENTITY_AUD ADD COLUMN OPERATIONAL_TRX BIT DEFAULT 0;
